[package]
name = "benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
fastvec = { path = "../" }
rand = "0.9"
criterion = { version = "0.8", features = ["html_reports"]}
smallvec = "2.0.0-alpha.12"

[[bench]]
name = "main"  # 对应文件名
harness = false

